    apiVersion: v1
    kind: Service
    metadata:
      name: ia-service
      namespace: monitoring
    spec:
      selector:
        app: ia-service
      ports:
        - protocol: TCP
          port: 5001
          targetPort: 5001
