    apiVersion: v1
    kind: Service
    metadata:
      name: banking-api-service
      namespace: banking-app      # <-- Ajout du namespace
    spec:
      selector:
        app: banking-api
      ports:
        - name: http 
          protocol: TCP
          port: 80
          targetPort: 5000